# Generated by Django 2.2.4 on 2019-12-30 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'Income',
            },
        ),
    ]
