# Generated by Django 2.2.4 on 2019-12-30 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(max_length=100)),
                ('counselor', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'inquery',
            },
        ),
    ]
